### ISSUE TITLE
Arrow keys are incorrect

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shell-shortcuts#16]
The 'Increase Window Size' and 'Decrease Window Size' sections but have down arrow keys instead of one down and one up arrow key. 

![Screenshot from 2020-04-29 08-07-44](https://user-images.githubusercontent.com/4884946/80607331-9c901280-89f2-11ea-8d31-375c6f58aea2.png)

**Comment by WatchMkr** [comment]
Fixed
