### ISSUE TITLE
The shortcuts window does not tile to small sizes well

### ISSUE THREAD

**Issue by leviport** [pop-os/shell-shortcuts#2]
The window will not get much smaller than quarter-size on my 1920x1080 display.
![Screenshot from 2020-03-24 09-31-54](https://user-images.githubusercontent.com/13512097/77445741-13fad280-6db3-11ea-886c-558335908608.png)
When it's quarter-sized, it does not show many shortcut items, meaning the user has to scroll through them. I'd like @maria-komarova 's thoughts -- are we ok with this the way it is? It's still usable at quarter-size, just probably not as good as it could be. 
![output](https://user-images.githubusercontent.com/13512097/77444900-0729af00-6db2-11ea-8562-8c2308631c19.gif)

**Comment by maria-komarova** [comment]
The idea was that one should be able to tile the window while learning the shortcuts. Hence, stacking the columns with shortcuts. It's too many of them so we will have to have scrolling.
I think the text is the main limitation here. I mean the width of the column of text containing the shortcut. So we can only go as narrow as the text allows. Quarter window is probably good.
The images can get even a bit smaller than necessary.

**Comment by brs17** [comment]
I could imagine, that people want to have this open to recall the keyboard shortcut (I want to move this window to another workspace but I don't remember what the shortcut is), if that is the case, the monitors taking up half of the page, is not a good use of limited space. Would it be possible to scale the displays down?

**Comment by WatchMkr** [comment]
The list will scale down well. As @brs17 suggested, the displays need to become smaller as the window size decreases.

**Comment by maria-komarova** [comment]
I agree that the list will scale down well. But we probably want to avoid keycaps with shortcuts wrapping to the next line. That's what I meant by the text being a limitation. Just want to clarify.

**Comment by WatchMkr** [comment]
Should be good now.
