### ISSUE TITLE
Typo in keyboard shortcuts 

### ISSUE THREAD

**Issue by maxwelldb** [pop-os/shell-shortcuts#20]
Just updated to 20.04 (awesome job!). I noticed a typo in the keyboard shortcuts guide:

![image](https://user-images.githubusercontent.com/50179998/80810762-7ef9af00-8b92-11ea-916c-6addb02f83ea.png)

"worksapce" -> "workspace"

PR #19 fixes this, as far as I can tell, but it's my first pop!_os-related commit.

**Comment by brs17** [comment]
#19 looks good as was merged! Thank you for your contribution!
