### ISSUE TITLE
Shortcuts aren't working as they supposed to

### ISSUE THREAD

**Issue by KarkanAlzwayed** [pop-os/shell-shortcuts#22]
Back on 19.10, all of the keyboard shortcuts worked flawlessly. Now on 20.04 some works. Pressing ctrl+super+ direction keys only works up, down and left. The right doesn't work. If I try to move one window to the left and the other to the right, I can only move them to the left. The right is not doing anything. I have clean installed the OS three times thinking that I had a bad install but to no avail.
Thank you

edit: After fiddling around, I found out that disabling the "pop shell" extension restores that functionality. I don't know if that is intentional or a bug.

**Comment by WatchMkr** [comment]
Hi @kylewill. Super+Enter and direction keys are the new default for moving windows on and between displays. Super + Ctrl + left/right can be set in keyboards shortcuts if so desired.
