### ISSUE TITLE
Shortcuts window opens in tiling mode, but children of it are in floating mode

### ISSUE THREAD

**Issue by leviport** [pop-os/shell-shortcuts#3]
If I run `pop-shell-shortcuts`, the shortcuts window opens in tiling mode. If I have the shortcuts window active and open another application, that application opens in floating mode.

~I'm also wondering if making the shortcuts window open only in floating mode (much like screenshots) is a good way to deal with https://github.com/pop-os/shell-shortcuts/issues/2~ Never mind, it is designed to be tiled so it can be used as a reference.

**Comment by WatchMkr** [comment]
I can't replicate this at this point. Please re-open if it occurs with the latest release.
