### ISSUE TITLE
Show desktop Keyboard Shortcut is missing in v20.04

### ISSUE THREAD

**Issue by ravijagga** [pop-os/shell-shortcuts#31]
`Super+D` keyboard shortcut to `Show Desktop` icons is not registered in `Keyboard Shortcuts`. Need help as I use this shortcut quite frequently.

**Comment by ids1024** [comment]
It seems Gnome calls this "Hide all normal windows", which you can find in the "Navigation" section of Keyboard Shortcuts in Settings.

**Comment by ravijagga** [comment]
Thanks @ids1024, `Hide all normal windows` shortcut was empty by default. Assigned a shortcut there. :)
