### ISSUE TITLE
Contents scrolls after resizing and before un-focusing

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell-shortcuts#32]
When the shortcuts list is maximized on a 1080p display (for example), the shortcuts split into two columns, allowing everything to be viewed without scrolling; however, scrolling is still possible:

![pop-shell-shortcuts-scrolling](https://user-images.githubusercontent.com/7199422/90194269-1a024780-dd84-11ea-97a5-4c5a9560b5f9.png)

Scrolling is only possible until the window is un-focused; once it's un-focused, the scrollbar moves back to the top by itself, and does not appear again after the window is re-focused.

It would be preferable if the scrollbar went away as soon as all of the contents is visible.

**Comment by ids1024** [comment]
Appears to be related to this code: https://github.com/pop-os/shell-shortcuts/blob/14100a9bb6bd7660615441da05b32ea21ef4e8af/src/app.rs#L283-L293

Commenting out either/both `.set_margin_*()` calls seems to prevent this behavior. Not sure exactly why.

**Comment by ids1024** [comment]
Fixed in https://github.com/pop-os/shell-shortcuts/pull/37.

Closing.
