### ISSUE TITLE
Shortcut to power off

### ISSUE THREAD

**Issue by felops** [pop-os/shell-shortcuts#33]
Hi everyone,

Just moved to Pop!_OS this week and I am really enjoying it, great work you all have done!

I was thinking about a shortcut to power off the computer. Is there room for it? Also, I was thinking to leave <kbd>super</kbd> + <kbd>L</kbd> to block the computer and actually <kbd>super</kbd> + <kbd>ESC</kbd> to power off. What do you think?

**Comment by mmstick** [comment]
Accidentally powering off the system with a shortcut would be pretty drastic

**Comment by felops** [comment]
Hey @mmstick, there is a confirmation before, at least in GNOME (and so current version of Pop!_OS), so I don't think you could accidentally power off the system just like that. Do you think so?

**Comment by felops** [comment]
What I mean it's just a shortcut to hit and open the confirmation to shut down the system (as GNOME does), and not shutdown right after you press the shortcut.
