### ISSUE TITLE
Should we include Super+O and Super+G?

### ISSUE THREAD

**Issue by leviport** [pop-os/shell-shortcuts#4]
<kbd>Super</kbd> + <kbd>O</kbd> (O as in Oscar, not Zero) and <kbd>Super</kbd> + <kbd>G</kbd> seem like they will be very useful for using tiling mode, and I'm wondering if they're important enough to include in pop-shell-shortcuts. @maria-komarova what do you think of this?

For reference: 
<kbd>Super</kbd> + <kbd>O</kbd> = toggle column vs row tiles
<kbd>Super</kbd> + <kbd>G</kbd> = toggle a window between tile mode and float mode

**Comment by leviport** [comment]
Oh, and would we want to also include <kbd>Super</kbd> + mouse dragging to move windows? I've found it to be useful, so I'm betting other people will use it as well.

**Comment by maria-komarova** [comment]
Are we talking about the Shortcuts help? Super + O and Super + G should be there according to the design. The mockup for the reference. I believe we have talked with @WatchMkr about the Super + mouse drag but decided to not include it. It didn't feel like a Pop Shell specific shortcut. 
images.githubusercontent.com/57502897/77457982-12d1a180-6dc3-11ea-8ada-d0ad4b349ed0.png)

**Comment by leviport** [comment]
Ah ok, I think the current version just hasn't been updated to have them then. 

Is the fact that Super + mousedrag isn't part of pop-shell a meaningful distinction for users though? If it makes it easier to use pop-shell, should it be included, regardless of where it came from?

**Comment by maria-komarova** [comment]
The Shortcuts help window is for the Pop Shell and the changes associated with it. So it might not be the best place for this shortcut. 
You are right that it might be useful to know this shortcut if one chooses to hide titlebars. Bit this is supposed to be placed in the GNOME extensions as additional settings. So I wonder where the Super + mousedrag should live. 
Does anyone know if it appears anywhere in keyboard shortcut helps and menus currently?

**Comment by leviport** [comment]
I'm not certain there is a shortcut help section in default gnome. They might just expect keyboard shortcut settings, which lists them all, to be the definitive list.

**Comment by maria-komarova** [comment]
That might mean that this shortcut doesn't show anywhere at all.

**Comment by leviport** [comment]
:thinking: I guess I haven't seen mouse dragging related shortcuts listed anywhere, now that I think about it. Like dragging the window to the sides for half-tiling, or to the top to maximize it.

**Comment by WatchMkr** [comment]
Completed
