### ISSUE TITLE
Add stacking-related shortcuts

### ISSUE THREAD

**Issue by leviport** [pop-os/shell-shortcuts#40]
https://github.com/pop-os/shell/pull/481 was merged on Friday. but I don't think this awesome new feature is very discoverable in the OS at all. Adding them here seems like a good place to start.

**Comment by ids1024** [comment]
I was just thinking of this. And it should probably be listed in Gnome Control Center as well.

**Comment by RickDW** [comment]
Is there a list of stacking related keybindings somewhere? I can't seem to find them.

**Comment by mmstick** [comment]
Soon. I'm working on releasing it today

**Comment by mmstick** [comment]
https://github.com/pop-os/shell-shortcuts/commit/a653635e0f4774a5f6983a790ebf2d44c72035e0
