### ISSUE TITLE
x86_64' is not a recognized processor for this target

### ISSUE THREAD

**Issue by GitGangGuy** [pop-os/shell-shortcuts#43]
I'm installing/compiling this program for my Arch GNU/Linux machine over an unofficial [AUR package](https://aur.archlinux.org/packages/pop-shell-shortcuts-git/). According to its [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pop-shell-shortcuts-git) file, it calls `make prefix=/usr` to compile during the `build()` step, which fails. I get the following error during compilation:
```
==> Starting build()...
cargo build "--release"
   Compiling proc-macro2 v1.0.10
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.18
   Compiling serde v1.0.115
'x86_64' is not a recognized processor for this target (ignoring processor)
[...]
'x86_64' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
error: could not compile `unicode-xid`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
'x86_64' is not a recognized processor for this target (ignoring processor)
[...]
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
error: build failed
make: *** [Makefile:57: target/release/pop-shell-shortcuts] Error 101
```
Is this an issue with your Makefile or my system?

**Comment by ids1024** [comment]
Not sure what's going on. The `Makefile` doesn't seem to pass any funny arguments related to targets (just using the default), and I don't see anything strange in the `PKGBUILD`. Perhaps some env var present during the build is causing issues?

**Comment by GitGangGuy** [comment]
Turns out this was an issue with my compile flags. I accidentally set `-Ctarget-cpu` to my CPU architecture instead of its codename (`haswell`, in my case). That fixed it, sorry for wasting your time.
