### ISSUE TITLE
Shell Shortcuts window is too small by default

### ISSUE THREAD

**Issue by isantop** [pop-os/shell-shortcuts#8]
When opening the Shell Shortcuts page, the window is too small to be useful by default, requiring that the window be resized to a much larger size in order to view anything. This doesn't happen in tiling mode because the tiling WM resizes the window as part of the tiling, however the "View All" link is still present by default with tiling disabled, and it looks broken having the window open up so small.

Using `pop-shell 0.1.0~1586823586~20.04~63b89d0`, up-to-date from APT as of 2020-04-14 at 12:16pm. 

Screenshot attached:

![Screenshot from 2020-04-14 12-16-02](https://user-images.githubusercontent.com/5883565/79259453-f963c880-7e49-11ea-9b5b-1cf4f35dc5d7.png)

**Comment by mmstick** [comment]
Just needs the minimum window dimensions to be supplied on the ApplicationWindow
